# This file defines a ClusterIssuer for Let's Encrypt staging environment using cert-manager.
# Make sure to replace YOUR_EMAIL_ADDRESS_HERE with your actual email address.
# This ClusterIssuer will be used to issue certificates for your Ingress resources.


apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dev
spec:
  acme:
    server: https://acme-dev-v02.api.letsencrypt.org/directory
    email: # YOUR_EMAIL_ADDRESS_HERE (e.g., admin@yourdomain.com)
    privateKeySecretRef:
      name: letsencrypt-dev-key
    solvers:
    - http01:
        ingress:
          class: nginx # This tells cert-manager to use the NGINX Ingress to solve the challenge